# Listas e manipulação de listas


In [ ]:
l = [] # Criando uma lista vazia

l.append("Esdras") # adicionando itens no final da lista com o método append
l.append("Brenda")
l.append("Maria")
l.append("PH")
l.append("lucas")
l.append("Dos pode")
l.append("Dos pode")
print(l)

l.insert(1, "Ema") # Utilizando o método insert para colocar um item em uma posição especifica
print(l)

l.remove("Ema") # Utilizando o método remove para remover um item da lista
print(l)

l.pop() # Utilizando o método pop para remover o último item da lista
print(l)

indice = l.index("Maria") # Método indice retorna a posição do elemento em questão na primeira ocorrência
print(f"Maria está na posição {indice}")

quantidade = l.count("Dos pode") # Conta quantos elementos especificos tem nessa lista
print(quantidade)

l.sort() # Ordena a lista
print(l)

l.reverse() # Reverte a lista
print(l)

copia = l.copy() # Cria uma copia da lista
print(copia)

l.clear() # Remove todos os itens
print(l)


['Esdras', 'Brenda', 'Maria', 'PH', 'lucas', 'Dos pode', 'Dos pode']
['Esdras', 'Ema', 'Brenda', 'Maria', 'PH', 'lucas', 'Dos pode', 'Dos pode']
['Esdras', 'Brenda', 'Maria', 'PH', 'lucas', 'Dos pode', 'Dos pode']
['Esdras', 'Brenda', 'Maria', 'PH', 'lucas', 'Dos pode']
Maria está na posição 2
1
['Brenda', 'Dos pode', 'Esdras', 'Maria', 'PH', 'lucas']
['lucas', 'PH', 'Maria', 'Esdras', 'Dos pode', 'Brenda']
['lucas', 'PH', 'Maria', 'Esdras', 'Dos pode', 'Brenda']
[]


# Praticando slice com listas

In [ ]:
carros = ["Gol", "Sandero", "Palio", "lancer"]
print(carros)
print(carros[1:])
print(carros[::-1])

['Gol', 'Sandero', 'Palio', 'lancer']
['Sandero', 'Palio', 'lancer']
['lancer', 'Palio', 'Sandero', 'Gol']


# Percorrendo listas

In [ ]:
eletronicos = ["Notebook", 'Drone', 'Iphone', 'TV', "Tablet"]

for item in eletronicos:
    print(item)

Notebook
Drone
Iphone
TV
Tablet


# List Comprehension --> é uma forma compacta e eficiente de criar listas, simplificando a escrita de código e tornando-o mais legível.


In [ ]:
lista = [1, 3, 5, 91, 8, 9, 6, 12]

cauculo = [n ** 2 for n in lista if n % 2 == 0]  # Se perceber bem é a mesma coisa de fazer um for e uma condição, apenas esta comprimida dentro da lista
print(cauculo)

[64, 36, 144]


# Diferença entre Listas e tuplas



# Listas são Mutaveis ou seja podem ser alteradas

In [ ]:
frutas = ["Maçã", "banana", 'Uva', 23, 88, 1.89, True]
print(frutas)

frutas.append("Melancia")
print(frutas)

posicao = frutas.index(23)
print(f'o número 23 está na posição {posicao}')

frutas[0] = 'Goiaba'
print(frutas)

['Maçã', 'banana', 'Uva', 23, 88, 1.89, True]
['Maçã', 'banana', 'Uva', 23, 88, 1.89, True, 'Melancia']
o número 23 está na posição 3
['Goiaba', 'banana', 'Uva', 23, 88, 1.89, True, 'Melancia']


# Ao contrario de listas , tuplas são imutaveis elas não se alteram

In [ ]:
filmes = ("Coraline", 'Sonic', 'Sherk')
print(filmes)

# filmes[0] = "Madascar"
# print(filmes)   claramente dará um VALUEERROR

# Porém ainda conseguimos vizualizar os dados dessa lista
quantidade_filmes = len(filmes)
print(f'Temos {quantidade_filmes} filmes nessa lista')

('Coraline', 'Sonic', 'Sherk')
Temos 3 filmes nessa lista


# Funções

# 1 - Função sem parâmetro e sem retorno

In [ ]:
def recepcao():                           # Em funções sem parâmetro e sem retorno é a forma mais inicial de entender uma função
    print('Olá mundo!')

recepcao()
recepcao()                     # Voce pode chamar a função quantas vezes quiser



Olá mundo!
Olá mundo!


# 2 - Função com passagem de parâmetro

In [ ]:
def mensagem(texto): # Como se fosse uma variavel sem atribuição de valor
    print(texto) # o print é essencial para mostrar o resultado que você quer na função

mensagem('Texto 1') # Quando se chama a função para mostrar o resultado, é como se colocasse um valor
mensagem('Texto 2') # de atribuição para a variavel, que no caso é o parametro texto

def somar(a, b): # Mesma coisa em funções de soma
    print(a + b)

somar(2, 3)
somar(3, 3)

Texto 1
Texto 2
5
6


# 3 - Função com passagem de parâmetros e retorno

In [ ]:
''' A única diferença entre esse outro tipo de função é que se usa o return. Ao contrario do print ele vai retornar o que voce quer de resultado
   e não vai printar como o print faz '''

def multiplicacao(x, z):
    return x * z

resultado = multiplicacao(3, 3)  # E no resultado é convencional chamar a função dentro de uma variavel
print(resultado)


def cauculo_imc(p, h):    # P é o primeiro primeiro parâmetro que vai assumir o valor do peso da pessoa
    return p / h ** 2     # H é o segundo parâmetro que vai assumir o valor de altura

r = cauculo_imc(77, 1.74)
print(f'O seu imc é de {r:.2f}')  # No resultado utilizei F string apenas para colocar duas casas decimais , mas poderia apenas colocar a variavel r não iria
                                  # alterar em nada o resultado

9
O seu imc é de 25.43


# Matrizes


In [ ]:
import numpy as np  # importando a biblioteca numpy que é bastante utlizada em matrizes

matriz = np.array([[2, 4, 5],
                   [3, 5, 7]])  # matriz de 2 linhas e 3 colunas

print(matriz)



[[2 4 5]
 [3 5 7]]


# Shape mostra o formato dessa matriz

In [ ]:
print(matriz.shape) # Como eu mostrei anteriormente 2 linhas por 3 colunas

(2, 3)


# A seguir retornarei a linhas dessa matriz separadamente

In [ ]:
print(matriz[0]) # Primeira linha , assim como em uma lista normal conseguimos achar determinado valor por indices

[2 4 5]


In [ ]:
print(matriz[1]) # segunda linha

[3 5 7]


# Retornando colunas


In [ ]:
# Para retornarmos colunas utilizaremos dois colchetes [][]

print(matriz[0][0]) # Primeiro colchete vai a linha e o segundo vai a coluna

2


In [ ]:
print(matriz[1][2])

7


# Percorrendo Matrizes

In [ ]:
# Primeiro vamos precisar do formato dessa matriz , vamos usar o shape
print(matriz.shape)  # resultado (2, 3) 2 linhas e 3 colunas
                                # 0  1  posição
separa = 25 * '-'   # Ignora isso rapaziada
print(separa)

# vamos utilizar o laço for , linhas está na posição 0 então vamos retornar elas
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]): # percorrer as colunas é a mesma ideia de antes dois [][] pra informar a linha e coluna
        print(matriz[i][j])          # Não tem como acessar colunas sem as linhas





''' Importante frizar sobre matrizes, utilizamos a biblioteca numpy e o metodo array para criar a matriz
como pode se observar no primeiro codigo '''


(2, 3)
-------------------------
[2 4 5]
2
4
5
[3 5 7]
3
5
7


#Vetor (Array)

In [ ]:
""" Vetor é basicamente igual a lista, única diferença é que vetor voce so vai colocar um tipo de dado e o ARRAY ajuda nessa questão  """

import array # Importanto array

numeros = array.array('i', [2, 3, 6, 8]) # 'i' especifiquei que vai ser um vetor so de números inteiros
print(numeros)

# O resto é igual a lista adiciono com append, removo com remove e assim por diante

# POR EXEMPLO

temperatura_no_tocantins = array.array('f', [40.5, 36.5, 46.0, 50.5]) # Todos os dados são float , e se tentar colocar outro dado que não seja float da ERRO
print(temperatura_no_tocantins)

print('Temperatura mais alta', temperatura_no_tocantins[3])

array('i', [2, 3, 6, 8])
array('f', [40.5, 36.5, 46.0, 50.5])
Temperatura mais alta 50.5


In [ ]:
# Percorrendo o vetor, mesma coisa de matriz

for t in temperatura_no_tocantins:
    print(t)

40.5
36.5
46.0
50.5


# Pilhas

In [ ]:
''' LIFO = Last In, First Out
O último elemento que entra é o primeiro a sair''' # Mais fácil de entender do que fila



pilha = [] # Criando lista vazia

pilha.append("Esdras") # adicionando elementos
pilha.append("PH")
pilha.append("Neguim")
pilha.append("Renato")
pilha.append("Kevin")
pilha.append("Vitin Amador")
pilha.append("Dos Pode")

print(pilha)


# agora vamos revomer o ultimo elemento pra entender que o ultimo que entrou é o primeiro a sair

removendo_ultimo_elemento = pilha.pop()
print(f'Ultimo elemento: {removendo_ultimo_elemento}') # vai me retornar o elemento que foi removido

print("Pilha atualizada")
print(pilha) # Verificando a pilha novamente, e é assim sucessivamente

removendo_ultimo_elemento = pilha.pop() # pop() sempre remove o ultimo elemento
print(removendo_ultimo_elemento)

print(pilha)


['Esdras', 'PH', 'Neguim', 'Renato', 'Kevin', 'Vitin Amador', 'Dos Pode']
Ultimo elemento: Dos Pode
Pilha atualizada
['Esdras', 'PH', 'Neguim', 'Renato', 'Kevin', 'Vitin Amador']
Vitin Amador
['Esdras', 'PH', 'Neguim', 'Renato', 'Kevin']


# Filas

In [ ]:
''' FIFO = First In, First Out
O primeiro elemento que entra é o primeiro a sair'''

# Filas é um pouco complexo pois exige Função mas é dboa

# Em Filas não é muito connvencional utilizar listas , vamos utilizar deque

from collections import deque  # Importando deque para usar como fila

fila_de_motos = deque() # Criando fila com deque

def adicionar_moto(fila, moto): # Usando função para adiconar as motos
    fila.append(moto)

adicionar_moto(fila_de_motos, "Honda 250")  # chamando função de acordo com os parametros
adicionar_moto(fila_de_motos, "Fan 160")
adicionar_moto(fila_de_motos, "BMW 650")

print("Lista de atualizada de motos")
print(fila_de_motos)

def primeiro_elemento(fila):        # Nessa parte vamos remover o primeiro pedido que no caso é a Honda 250 , ela foi a primeira a entrar então vai ser
    return fila_de_motos.popleft()  # a primeira a sair , popleft serve pra isso

resultado = primeiro_elemento(fila_de_motos)
print(resultado)

print('Fila atualizada')
print(fila_de_motos)


# vamos verificar se a fila está vazia

def fila_vazia(fila):
    return len(fila_de_motos) == 0

fila_vazia_ou_cheia = fila_vazia(fila_de_motos)  # Irá retornar False , pois ainda tem duas motos
print(fila_vazia_ou_cheia)

Lista de atualizada de motos
deque(['Honda 250', 'Fan 160', 'BMW 650'])
Honda 250
Fila atualizada
deque(['Fan 160', 'BMW 650'])
False
